[project]
name = "pipeline-btw"
version = "0.1.0"
description = "Writing a baby pipeline btw"
readme = "README.md"
authors = [
    { name = "Kieran Pedrick", email = "kieran@aileks.dev" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-sqlite>=1.10.0",
    "httpx>=0.28.1",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.5",
]

[project.scripts]
pipeline-btw = "pipeline_btw:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "sqlfluff>=4.3.0",
    "sqlfluff-templater-dbt>=4.3.0",
]
